[package]
name = "tcpmiddlebox"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = "0.34.0"
pnet_datalink = "0.34.0"
pnet_packet = "0.34.0"
rand = "0.8.5"
derive-new = "0.5"

[profile.release]
strip = true
lto = true
codegen-units = 1
